spring:
  application:
    name: none-proxy
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 100
      max-idle: 100
      max-wait: 1000
      min-idle: 10

#proxy port
proxy:
  port: 6666

#zk config
zk:
  #是否注册zk
  switch: true
  #zk地址
  addr: 0.0.0.0:2181
  #zk连接超时
  connect:
    timeout: 15000
  #zk注册的根节点
  root: /server

#spring端口
server:
  port: 8082

#路由算法
route:
  algorithm: "none"
